<?php

/**
 * @file
 * Contains clipboardjs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function clipboardjs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.clipboardjs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Clipboard.js') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function clipboardjs_theme($existing, $type, $theme, $path) {
  return [
    'clipboardjs_button' => [
      'variables' => [
        'value' => NULL,
        'label' => t('Click to copy'),
        'alert_style' => 'tooltip',
        'alert_text' => t('Copied!'),
        'height' => 13,
        'width' => 13,
        'attributes' => NULL,
      ],
    ],
    'clipboardjs_snippet' => [
      'variables' => [
        'value' => NULL,
        'label' => t('Click to copy'),
        'alert_style' => 'tooltip',
        'alert_text' => t('Copied!'),
        'height' => 13,
        'width' => 13,
        'attributes' => NULL,
      ],
    ],
    'clipboardjs_textarea' => [
      'variables' => [
        'value' => NULL,
        'label' => t('Click to copy'),
        'alert_style' => 'tooltip',
        'alert_text' => t('Copied!'),
        'height' => 13,
        'width' => 13,
        'attributes' => NULL,
      ],
    ],
    'clipboardjs_textfield' => [
      'variables' => [
        'value' => NULL,
        'label' => t('Click to copy'),
        'alert_style' => 'tooltip',
        'alert_text' => t('Copied!'),
        'height' => 13,
        'width' => 13,
        'attributes' => NULL,
      ],
    ],
    // @deprecated in clipboardjs:2.0.2 and is removed from clipboardjs:2.1.0.
    'clipboardjs' => [
      'variables' => [
        'text' => NULL,
        'value' => NULL,
        'label' => t('Click to copy'),
        'alert_style' => 'tooltip',
        'alert_text' => t('Copied!'),
        'height' => 13,
        'width' => 13,
        'attributes' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_library_info_alter().
 */
function clipboardjs_library_info_alter(&$libraries, $extension) {
  if ($extension === 'clipboardjs') {
    $default = \Drupal::service('library.libraries_directory_file_finder')->find('clipboard/dist/clipboard.js');
    $wikimedia = \Drupal::service('library.libraries_directory_file_finder')->find('clipboard.js/dist/clipboard.js');

    if (!$default && $wikimedia) {
      $libraries["clipboardjs"]["js"] = ['/' . $wikimedia => ''];
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @deprecated in clipboardjs:2.0.2 and is removed from clipboardjs:2.1.0. Use
 * the correct field formatters.
 * @see https://www.drupal.org/project/clipboardjs/issues/3273220
 */
function clipboardjs_preprocess_clipboardjs(&$variables) {
  $variables['attributes']['id'] = uniqid('clipboardjs-');
  $variables['module_path'] = base_path() . \Drupal::service('extension.list.module')->getPath('clipboardjs');
  if (isset($variables['text'])
    && $variables['text'] !== ''
    && !isset($variables['value'])) {
    $variables['value'] = $variables['text'];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function clipboardjs_preprocess_clipboardjs_button(&$variables) {
  $variables['attributes']['id'] = uniqid('clipboardjs-');
  $variables['module_path'] = base_path() . \Drupal::service('extension.list.module')->getPath('clipboardjs');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function clipboardjs_preprocess_clipboardjs_snippet(&$variables) {
  $variables['attributes']['id'] = uniqid('clipboardjs-');
  $variables['module_path'] = base_path() . \Drupal::service('extension.list.module')->getPath('clipboardjs');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function clipboardjs_preprocess_clipboardjs_textarea(&$variables) {
  $variables['attributes']['id'] = uniqid('clipboardjs-');
  $variables['module_path'] = base_path() . \Drupal::service('extension.list.module')->getPath('clipboardjs');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function clipboardjs_preprocess_clipboardjs_textfield(&$variables) {
  $variables['attributes']['id'] = uniqid('clipboardjs-');
  $variables['module_path'] = base_path() . \Drupal::service('extension.list.module')->getPath('clipboardjs');
}
