<?php

/**
 * Implements hook_theme().
 */
function product_search_theme($existing, $type, $theme, $path) {
  return [
    'product_search' => [
      'variables' => [
        'placeholder' => NULL,
        'marketingblock' => NULL,
        'results' => NULL,
      ],
      'template' => 'product_search',
    ],
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function product_search_preprocess_html(&$variables) {
  $variables['current_path'] = \Drupal::service('path.current')->getPath();
  $alias = \Drupal::service('path_alias.manager')->getAliasByPath($variables['current_path']);
  if ($alias !== $variables['current_path']) {
    $variables['current_path_alias'] = $alias;
  }
}
