<?php

/**
 * @file
 * Hook implementations for the SEO Audit module.
 */

/**
 * Implements hook_theme().
 */
function seo_audit_theme($existing, $type, $theme, $path) {
  return [
    'seo_audit_crawl_results_view' => [
      'variables' => [
        'id' => NULL,
        'title' => NULL,
        'url' => NULL,
        'created' => NULL,
        'completed' => NULL,
        'status' => NULL,
        'crawl_data' => [],
      ],
      'template' => 'seo-audit-crawl-results-view',
    ],
    'seo_audit_notification' => [
      'variables' => [
        'report_url' => NULL,
      ],
      'template' => 'seo_audit_notification',
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function seo_audit_mail($key, &$message, $params) {
  switch ($key) {
    case 'crawl_notify':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}
