name: Product Tags
type: module
description: 'Collects and displays unique tags from products relating to a shop.'
package: Custom
core_version_requirement: ^9 || ^10 || ^11
dependencies:
  - drupal:node
  - drupal:taxonomy
