<?php

/**
 * @file
 * Queue ui module file.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\queue_ui\Hook\AlterHooks;

// @phpstan-ignore-next-line
#[LegacyHook]
function queue_ui_queue_info_alter(&$queues) {// phpcs:ignore Drupal.Commenting.FunctionComment.Missing, Squiz.WhiteSpace.FunctionSpacing.Before
  \Drupal::service(AlterHooks::class)->queueInfoAlter($queues);
}
