<?php

/**
 * @file
 * Primary module hooks for footer_block module.
 */

/**
 * Implements hook_theme().
 */
function footer_block_theme($existing, $type, $theme, $path) {
  return [
    'footer_block' => [
      'variables' => [
        'content' => NULL,
      ],
      'template' => 'footer-block',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for footer_block.
 */
function footer_block_preprocess_footer_block(&$variables) {
  $variables['#attached']['library'][] = 'footer_block/footer-block';
}
