<?php

/**
 * @file
 * Allows to create multiple nodes using one page, one form submission.
 *
 * Unusable without Javascript, there's no degradation implemented.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\node\NodeTypeInterface;

/**
 * Implements hook_theme().
 */
function multi_node_add_theme() {
  return [
    'multi_node_add_list' => [
      'variables' => ['content' => NULL],
      'template' => 'multi-node-add-list',
    ],
  ];
}

/**
 * Prepares variables for list of available node type templates.
 *
 * Default template: node-add-list.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: An array of content types.
 *
 * @see node_add_page()
 */
function template_preprocess_multi_node_add_list(array &$variables) {
  $variables['types'] = [];
  if (!empty($variables['content'])) {
    foreach ($variables['content'] as $type) {
      $type_id = $type->id();
      $variables['types'][$type_id] = [
        'type' => $type_id,
        'add_link' => Link::createFromRoute($type->label(), 'multi_node_add.add', ['node_type' => $type_id]),
        'description' => ['#markup' => $type->get('description')],
      ];
    }
  }
}

/**
 * Implements hook_form_alter().
 *
 * Modifies the node form according to the multi_node_add_page() form config.
 */
function multi_node_add_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_state->has('multi_node_add_hijacked') || $form_state->has('multi_node_add_fields_show')) {
    $form['#after_build'][] = 'multi_node_add_node_form_after_build';

    if (isset($form['actions']['submit'])) {
      $form['actions']['submit']['#submit'][] = 'multi_node_add_node_form_submit';
    }

    if (!$form_state->has('multi_node_add_fields_show')) {
      $fields = \Drupal::routeMatch()->getParameter('fields');
      $fields = is_string($fields) ? explode(',', $fields) : [];
      $form_state->set('multi_node_add_fields_show', array_filter($fields));
    }
  }
}

/**
 * Modifies the node form according to the choices of the user.
 */
function multi_node_add_node_form_after_build($form, FormStateInterface $form_state) {
  unset($form['actions']['preview']);

  if (isset($form['actions']['submit'])) {
    $form['actions']['submit']['#value'] = t('Create');
  }

  unset($form['advanced']);
  $field_names = array_keys($form);

  $node_type = \Drupal::routeMatch()->getParameter('node_type');
  $node_type_id = $node_type instanceof NodeTypeInterface ? $node_type->id() : $node_type;
  $fields = \Drupal::service('entity_field.manager')->getFieldDefinitions('node', $node_type_id);
  $fields_show = $form_state->get('multi_node_add_fields_show') ?: [];

  foreach ($field_names as $field_name) {
    if (isset($fields[$field_name]) && !in_array($field_name, $fields_show, TRUE)) {
      $form[$field_name]['#access'] = FALSE;
    }
  }
  return $form;
}

/**
 * Redirects the iFrame to the simple result page instead of full node page.
 *
 * @todo: make it work, even not called actually.
 */
function multi_node_add_node_form_submit($form, FormStateInterface $form_state) {
  // $form_state->setRedirect('multi_node_add.status', [
  //   'node_type' => \Drupal::routeMatch()->getParameter('node_type'),
  //   'nid' => $form_state->getValue('nid'),
  // ]);
}
